---
title: "Final project"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

Import all library
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Import data
```{r}
review_tb = as_tibble(read.csv("./data/reviews2020_0to5.csv"))
listing_tb = as_tibble(read.csv("./data/listings.csv"))
crime_tb = as_tibble(read.csv("./data/Crime_Data_from_2020_to_Present.csv"))
```

Import data
```{r}
# data_dict packeage
data_dict <- function(data, print_table = "No"){
  # packages
  suppressPackageStartupMessages(suppressWarnings(require(tidyverse)))
  suppressPackageStartupMessages(suppressWarnings(require(psych)))
  suppressPackageStartupMessages(suppressWarnings(require(ggpubr)))
  suppressPackageStartupMessages(suppressWarnings(require(gridExtra)))
  # get rid of scientific notation
  options(scipen = 999)
  # Get variable info and NAs
  var_info <- data.frame(Variable = names(data),
                         VariableType = sapply(data, class),
                         MissingValues = sapply(data, function(y) 
                           sum(length(which(is.na(y))))),
                         row.names = NULL)
  # get descriptive stats
  desc_stats <- data.frame(Variable = names(data), 
                           describe(data)[c(2:5, 13, 8:10)], 
                           row.names = NULL)
  # Create the data dictionary
  d_dict <- merge(var_info, desc_stats, by = "Variable")
  d_dict <- d_dict %>% mutate_at(vars("mean":"range"), .fun = round, 2)
  # NA's for summary stats of variables not of class numeric or integer
  d_dict <- d_dict %>%
    mutate(mean = ifelse(VariableType == "numeric" | VariableType == "integer", mean, ""),
           sd = ifelse(VariableType == "numeric" | VariableType == "integer", sd, ""),
           median = ifelse(VariableType == "numeric" | VariableType == "integer", median, ""),
           se = ifelse(VariableType == "numeric" | VariableType == "integer", se, ""),
           min = ifelse(VariableType == "numeric" | VariableType == "integer", min, ""),
           max = ifelse(VariableType == "numeric" | VariableType == "integer", max, ""),
           range = ifelse(VariableType == "numeric" | VariableType == "integer", range, ""))
  # return the result
  if(print_table == "No"){
    return(d_dict)
  } else {
    #create table if table = TRUE
    d_dict <- ggtexttable(d_dict,
                          rows = NULL)
    return(d_dict)
  }
}
# Data overview
data_dict(review_tb, print_table = 'Yes')
data_dict(listing_tb, print_table = 'Yes')
data_dict(crime_tb, print_table = 'Yes')
```

Group the same housing
```{r}
# Take average of the score by grouping the housing
avg_scorr_tb = review_tb %>%
  group_by(listing_id) %>%
  summarise(avg_score = mean(score))
hist(avg_scorr_tb$avg_score, main='Avg score distribution of all housings', xlab="Avg score")
```



```{r}
join_tb = left_join(avg_scorr_tb, listing_tb, c('listing_id'='id'))
join_tb$neighbourhood_group = factor(join_tb$neighbourhood_group)
join_tb$neighbourhood = factor(join_tb$neighbourhood)
join_tb$room_type = factor(join_tb$room_type)
data_dict(join_tb, print_table = 'Yes')
summary(join_tb)
```

EDA data
```{r}
# count all attributes
library(ggpubr)
g1 = ggplot(join_tb) + geom_bar(aes(x=neighbourhood_group)) 
g2 = ggplot(join_tb) + geom_histogram(aes(x=avg_score), binwidth=0.1)
g3 = ggplot(join_tb) + geom_bar(aes(x=room_type))
g4 = ggplot(join_tb) + geom_histogram(aes(x=availability_365),  binwidth=10)
ggarrange(g1,g2,g3,g4)
distinct(join_tb, neighbourhood)
g5 = ggplot(join_tb) + geom_bar(aes(x=neighbourhood)) 

# neighbourhood_group vs. price
distinct(join_tb, neighbourhood_group)
ggplot(join_tb) + geom_boxplot(aes(x=neighbourhood_group, y=price)) + ylim(0, 300)
ggplot(join_tb) + geom_violin(aes(x=neighbourhood_group, y=price)) + ylim(0, 300)
plot(join_tb$neighbourhood_group, join_tb$price, ylim=c(1, 300))

# neighbourhood vs. price
distinct(join_tb, neighbourhood)
ggplot(join_tb) + geom_boxplot(aes(x=neighbourhood, y=price)) + ylim(0, 300)
ggplot(join_tb) + geom_violin(aes(x=neighbourhood, y=price)) + ylim(0, 300)
plot(join_tb$neighbourhood, join_tb$price, ylim=c(1, 300))

# room_type vs. price
distinct(join_tb, room_type)
ggplot(join_tb) + geom_boxplot(aes(x=room_type, y=price)) + ylim(0, 500)
ggplot(join_tb) + geom_violin(aes(x=room_type, y=price)) + ylim(0, 500)
plot(join_tb$room_type, join_tb$price, ylim=c(1, 400))

# avg_score vs. price
ggplot(join_tb) + geom_point(aes(x=avg_score, y=price)) + geom_smooth(aes(x=avg_score, y=price)) + ylim(0, 5000)

# avg_score vs. price vs. neighbourhood_group
ggplot(join_tb) + geom_point(aes(x=avg_score, y=price, color=neighbourhood_group))

# avg_score vs. price vs. room_type
ggplot(join_tb) + geom_point(aes(x=avg_score, y=price, color=room_type))
```



```{r}
ggplot(join_tb) + geom_count(aes(x=neighbourhood_group, y = neighbourhood))
ggplot(join_tb) + geom_count(aes(x=neighbourhood_group, y = room_type))
```



```{r}
summary(crime_tb)
distinct(crime_tb, Crm.Cd.Desc)
crime_tb$Crm.Cd.Desc = factor(crime_tb$Crm.Cd.Desc)
```



```{r}

```



```{r}

```


```{r}

```